spring.application.name=backend
server.port=8081

spring.datasource.url=jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.disfyfckncbjhbmzuwmu
spring.datasource.password=${SUPABASE_PASSWORD}

# URL du Realm dans ton Docker Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/soutenancia
# Optionnel : désactiver la validation du certificat si tu n'es pas en HTTPS en local
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/soutenancia/protocol/openid-connect/certs

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
# --- Keycloak Administration Config ---
keycloak.server-url=http://localhost:8180
keycloak.realm=master
keycloak.client-id=admin-cli
keycloak.username=admin
keycloak.password=admin
keycloak.app-realm=soutenancia