spring.application.name=backend
server.port=8081

spring.datasource.url=jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.disfyfckncbjhbmzuwmu
spring.datasource.password=${SUPABASE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
# --- Keycloak Administration Config ---
keycloak.server-url=http://localhost:8180
keycloak.realm=master
keycloak.client-id=admin-cli
keycloak.username=admin
keycloak.password=admin
keycloak.app-realm=soutenancia